name: jan_suraksha
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #  # For API services
  #  gstmobieservice_marketplace:
  #    git:
  #      url: https://github.com/capitawrld/gstsahaymobileappservice_marketplace.git
  #      ref: main

  # For Get state management
  get: ^4.6.5

  # For responsive UI
  flutter_screenutil: 5.7.0

  # For svg picture support
  flutter_svg: ^2.0.7
  flutter_string_extractor: 0.1.0
  expandable: ^5.0.1
  http: ^0.13.5

  # For encryption
  asn1lib: ^1.5.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  intl: ^0.18.1
  webcrypto: ^0.5.3
  yaml: ^3.1.2
  basic_utils: ^5.3.0
  url_launcher: ^6.1.14
  webviewx: ^0.2.2
  pdfx: ^2.4.0
  shared_preferences: ^2.2.1
  uuid: ^3.0.7
  path_provider: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/dashboard/
    - assets/images/scheme/
    - assets/images/bankselection/
    - assets/images/responsepage/
    - assets/images/profile/
    - assets/files/
    - js_logo.svg
    - splash.png
    - splash_text.svg
    - splash_logo.svg
    - modiji.png
    - assets/mocks/
    - assets/config/

  fonts:
    - family: OutfitBold
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
    - family: OutfitRegular
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    - family: OutfitSemiBold
      fonts:
        - asset: assets/fonts/Outfit-SemiBold.ttf
    - family: OutfitExtraBold
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
    - family: OutfitLight
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
    - family: OutfitMedium
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
  #    - family: OutfitItalic
  #      fonts:
  #        - asset: assets/fonts/Outfit-Italic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
