name: jan_suraksha
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # For API services
  gstmobieservice_marketplace:
    git:
      url: https://github.com/capitawrld/gstsahaymobileappservice_marketplace.git
      ref: main

  # For Get state management
  get: ^4.6.5

  # For responsive UI
  flutter_screenutil: 5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: OutfitBold
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf
    - family: OutfitRegular
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    - family: OutfitSemiBold
      fonts:
        - asset: assets/fonts/Outfit-SemiBold.ttf
    - family: OutfitExtraBold
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
    - family: OutfitLight
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
    - family: OutfitMedium
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
#    - family: OutfitItalic
#      fonts:
#        - asset: assets/fonts/Outfit-Italic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
